/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Talita
 */
public class jfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();
       try 
    {
      UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
    } 
    catch (Exception e) 
    {
      e.printStackTrace();
    }
        SwingUtilities.updateComponentTreeUI(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuCadastro = new javax.swing.JMenu();
        jmAuto = new javax.swing.JMenuItem();
        jmModelo = new javax.swing.JMenuItem();
        jmCid = new javax.swing.JMenuItem();
        jmCadCliente = new javax.swing.JMenuItem();
        jmCadConce = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmPesAuto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmPesCid = new javax.swing.JMenuItem();
        jmPesCli = new javax.swing.JMenuItem();
        jmPesConc = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jdPrincipal.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        jdPrincipal.setForeground(java.awt.SystemColor.activeCaption);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo si.png"))); // NOI18N

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal);
        jdPrincipal.setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdPrincipalLayout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        jdPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        JMenuCadastro.setText("Cadastro");

        jmAuto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmAuto.setText("Automóvel");
        jmAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAutoActionPerformed(evt);
            }
        });
        JMenuCadastro.add(jmAuto);

        jmModelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jmModelo.setText("Modelo");
        jmModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModeloActionPerformed(evt);
            }
        });
        JMenuCadastro.add(jmModelo);

        jmCid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmCid.setText("Cidade");
        jmCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCidActionPerformed(evt);
            }
        });
        JMenuCadastro.add(jmCid);

        jmCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jmCadCliente.setText("Cliente");
        jmCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadClienteActionPerformed(evt);
            }
        });
        JMenuCadastro.add(jmCadCliente);

        jmCadConce.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jmCadConce.setText("Concessionária");
        JMenuCadastro.add(jmCadConce);

        jMenuBar1.add(JMenuCadastro);

        jMenu2.setText("Pesquisa");

        jmPesAuto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jmPesAuto.setText("Automóvel");
        jmPesAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPesAutoActionPerformed(evt);
            }
        });
        jMenu2.add(jmPesAuto);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem1.setText("Modelo");
        jMenu2.add(jMenuItem1);

        jmPesCid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jmPesCid.setText("Cidade");
        jmPesCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPesCidActionPerformed(evt);
            }
        });
        jMenu2.add(jmPesCid);

        jmPesCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jmPesCli.setText("Cliente");
        jMenu2.add(jmPesCli);

        jmPesConc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jmPesConc.setText("Concessionária");
        jMenu2.add(jmPesConc);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sobre");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jmCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCidActionPerformed
        jiCadCidade cadCidade = new jiCadCidade();
        jdPrincipal.add(cadCidade);
        cadCidade.setVisible(true);
    }//GEN-LAST:event_jmCidActionPerformed

    private void jmPesCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPesCidActionPerformed
        jiPesCidade pesCidade = new jiPesCidade();
        jdPrincipal.add(pesCidade);
        pesCidade.setVisible(true);
    }//GEN-LAST:event_jmPesCidActionPerformed

    private void jmCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadClienteActionPerformed
        jiCadCliente cadCliente = new jiCadCliente();
        jdPrincipal.add(cadCliente);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jmCadClienteActionPerformed

    private void jmAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAutoActionPerformed
        jiCadAuto cadAuto = new jiCadAuto();
        jdPrincipal.add(cadAuto);
        cadAuto.setVisible(true);
    }//GEN-LAST:event_jmAutoActionPerformed

    private void jmModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModeloActionPerformed
        // TODO add your handling code here:
        jiCadModelo cadModelo = new jiCadModelo();
        jdPrincipal.add(cadModelo);
        cadModelo.setVisible(true);
    }//GEN-LAST:event_jmModeloActionPerformed

    private void jmPesAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPesAutoActionPerformed
        jiPesAuto pesAuto = new jiPesAuto();
        jdPrincipal.add(pesAuto);
        pesAuto.setVisible(true);
    }//GEN-LAST:event_jmPesAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdPrincipal;
    private javax.swing.JMenuItem jmAuto;
    private javax.swing.JMenuItem jmCadCliente;
    private javax.swing.JMenuItem jmCadConce;
    private javax.swing.JMenuItem jmCid;
    private javax.swing.JMenuItem jmModelo;
    private javax.swing.JMenuItem jmPesAuto;
    private javax.swing.JMenuItem jmPesCid;
    private javax.swing.JMenuItem jmPesCli;
    private javax.swing.JMenuItem jmPesConc;
    // End of variables declaration//GEN-END:variables
}
