/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Bean.AutomovelBean;
import Bean.ModeloBean;
import DAO.AutomovelDAO;
import DAO.ModeloDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.LineBorder;
import javax.swing.plaf.metal.MetalBorders;

/**
 *
 * @author Talita
 */
public class jiCadAuto extends javax.swing.JInternalFrame {
    boolean salvar = false;
    int id = 0;
    List<ModeloBean> listaModelo = new ArrayList<ModeloBean>();
    /**
     * Creates new form jiCadAuto
     */
    public jiCadAuto() {
        initComponents();
        preencherModelos();
        salvar = true;
    }
    public jiCadAuto(AutomovelBean automovel) {
        initComponents();
        preencherModelos();
        salvar = false;
        id = automovel.getIdAutomovel();
    }
    
    private boolean validaCampos(){
        boolean validador = true;
        if(cbModelo.getSelectedIndex() == 0){
            validador = false;
            cbModelo.setBorder(new LineBorder(Color.RED));
            lbMensagem.setText("*Campos obrigatorios não preenchidos!");
        }else{
            cbModelo.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        txChassi.setText(txChassi.getText().trim());
        if(txChassi.getText().equals("")){
            validador = false;
            txChassi.setBorder(BorderFactory.createLineBorder(Color.red));
            lbMensagem.setText("*Campos obrigatorios não preenchidos!");
        }else{
            txChassi.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        txCor.setText(txCor.getText().trim());
        if(txCor.getText().equals("")){
            validador = false;
            txCor.setBorder(BorderFactory.createLineBorder(Color.red));
            lbMensagem.setText("*Campos obrigatorios não preenchidos!");
        }else{
            txCor.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        txAno.setText(txAno.getText().trim());
        if(txAno.getText().equals("")){
            validador = false;
            txAno.setBorder(BorderFactory.createLineBorder(Color.red));
            lbMensagem.setText("*Campos obrigatorios não preenchidos!");
        }else{
            txAno.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        }
        return validador;
    }
    
    private void preencherModelos(){
        cbModelo.removeAllItems();
    cbModelo.addItem("Selecione");
    try {
        
        listaModelo = ModeloDAO.pesquisar();
        for(ModeloBean modelo : listaModelo){
         cbModelo.addItem(modelo.getNome());
        }
    } catch (SQLException ex) {
        Logger.getLogger(CadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    private AutomovelBean retornaObjeto(){
        AutomovelBean automovel = new AutomovelBean();
        automovel.setModelo(listaModelo.get(cbModelo.getSelectedIndex()-1));
        automovel.setChassi(txChassi.getText());
        automovel.setCor(txCor.getText());
        automovel.setAno(Integer.parseInt(txAno.getText()));
        automovel.setIdAutomovel(id);
        return automovel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbModelo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txAno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbMensagem = new javax.swing.JLabel();
        txChassi = new javax.swing.JTextField();
        txCor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Automóvel");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 31, 140, -1));

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, -1, 20));
        jPanel1.add(txAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, -1));

        jLabel3.setText("Cor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        jLabel4.setText("Chassi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão salvar.png"))); // NOI18N
        btnSalvar.setBorder(null);
        btnSalvar.setBorderPainted(false);
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSalvarMouseReleased(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cancelar.png"))); // NOI18N
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelarMouseReleased(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        jPanel1.add(lbMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 20));
        jPanel1.add(txChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, -1));
        jPanel1.add(txCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));

        jLabel2.setText("Ano");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBounds(0, 0, 339, 306);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseReleased
    if (validaCampos()){
            try{
                if(salvar){
                    AutomovelDAO.inserir(retornaObjeto());
                    lbMensagem.setText("Salvo com sucesso");
                }else{
                    AutomovelDAO.alterar(retornaObjeto());
                    lbMensagem.setText("Salvo com sucesso");
                }
                this.dispose();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSalvarMouseReleased

    private void btnCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseReleased
       this.dispose();
    }//GEN-LAST:event_btnCancelarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JTextField txAno;
    private javax.swing.JTextField txChassi;
    private javax.swing.JTextField txCor;
    // End of variables declaration//GEN-END:variables
}
