/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Bean.AutomovelBean;
import Bean.CidadeBean;
import Bean.ClienteBean;
import Bean.EnderecoBean;
import DAO.AutomovelDAO;
import DAO.CidadeDAO;
import DAO.ClienteDAO;
import DAO.EnderecoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bruno
 */
public class jiCadCliente extends javax.swing.JInternalFrame {
    List<CidadeBean> listaCidade = new ArrayList<CidadeBean>();
    List<AutomovelBean> listaAutomovel = new ArrayList<AutomovelBean>();   
    boolean salvar = false;
    int id = 0;
    /**
     * Creates new form NovoJInternalFrame
     * @throws java.sql.SQLException
     */
    public jiCadCliente() throws SQLException {
        initComponents();
        preencherChassi();
    }
     private void preencherCidades(){
        if(cbEstado.getSelectedIndex() == 0){
            
        }else{
        cbCidade.removeAllItems();
        cbCidade.addItem("Selecione");
        try {
        listaCidade = CidadeDAO.pesquisar(cbEstado.getSelectedItem().toString());
        for(CidadeBean cidade : listaCidade){
         cbCidade.addItem(cidade.getNome());
            }
        }catch (SQLException ex) {
            Logger.getLogger(CadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
     
    private void preencherChassi() throws SQLException{
    listaAutomovel = AutomovelDAO.pesquisar();
    
    if(listaAutomovel == null){
     System.out.println("Nenhum veículo cadastrado");
    }else{
    for(AutomovelBean automovel : listaAutomovel){
         cbChassi.addItem(automovel.getChassi());
            }
    }
    
    }
    
    /*private void preencherCampos(ClienteBean cliente){
    txCidade.setText(cliente.getNome());
    cbEstado.setSelectedItem(cliente.getEstado());
    }*/
     
     private EnderecoBean cadastraEndereco() throws SQLException{
       EnderecoBean endereco = new EnderecoBean();
       endereco.setCidade(listaCidade.get(cbCidade.getSelectedIndex()-1));
       endereco.setNum(txNum.getText());
       endereco.setRua(txRua.getText());
       endereco.setIdEndereco(id);
       EnderecoDAO.inserir(endereco);  
       return EnderecoDAO.retornar();
     }
     private ClienteBean retornaObjeto() throws SQLException{
        ClienteBean cliente = new ClienteBean();
        cliente.setNome(txNome.getText().toUpperCase());
        cliente.setCpf(ftxCpf.getText());
        cliente.setTelefone(ftxTelefone.getText());      
        //cliente.setEstado(cbEstado.getSelectedItem().toString());
        cliente.setIdCliente(id);
        cliente.setEndereco(cadastraEndereco());
        cliente.setAutomovel(new AutomovelBean());
        cliente.getAutomovel().setIdAutomovel(1);

        return cliente;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSimNao = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxCpf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        ftxTelefone = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txNum = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCidade = new javax.swing.JComboBox();
        lbMensagem = new javax.swing.JLabel();
        rbtnSim = new javax.swing.JRadioButton();
        rbtnNao = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        cbChassi = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txModelo = new javax.swing.JTextField();
        txCor = new javax.swing.JTextField();
        txAno = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        txNome.setEnabled(false);
        jPanel3.add(txNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, -1));

        jLabel2.setText("CPF");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        try {
            ftxCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxCpf.setEnabled(false);
        jPanel3.add(ftxCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));

        jLabel3.setText("Telefone");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 20));

        try {
            ftxTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxTelefone.setEnabled(false);
        jPanel3.add(ftxTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 100, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 10));

        jLabel4.setText("Possui Cadastro?");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jLabel5.setText("Dados Pessoais");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 20));

        jLabel6.setText("Rua");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txRua.setEnabled(false);
        jPanel3.add(txRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, -1));

        jLabel7.setText("Nº");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 20));

        txNum.setEnabled(false);
        jPanel3.add(txNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 50, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.setEnabled(false);
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setText("UF");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        jLabel9.setText("Cidade");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 20));

        cbCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione" }));
        cbCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbCidade.setEnabled(false);
        jPanel3.add(cbCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));
        jPanel3.add(lbMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 20));

        btngSimNao.add(rbtnSim);
        rbtnSim.setText("Sim");
        rbtnSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbtnSimMouseReleased(evt);
            }
        });
        jPanel3.add(rbtnSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 20));

        btngSimNao.add(rbtnNao);
        rbtnNao.setText("Não");
        rbtnNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbtnNaoMouseReleased(evt);
            }
        });
        jPanel3.add(rbtnNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        jLabel10.setText("Cliente");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        cbCliente.setEnabled(false);
        jPanel3.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 10));

        jLabel11.setText("Endereço");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel12.setText("Chassi");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão salvar.png"))); // NOI18N
        btSalvar.setBorder(null);
        btSalvar.setBorderPainted(false);
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSalvarMouseReleased(evt);
            }
        });
        jPanel3.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 90, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cancelar.png"))); // NOI18N
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCancelarMouseReleased(evt);
            }
        });
        jPanel3.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        cbChassi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChassiActionPerformed(evt);
            }
        });
        jPanel3.add(cbChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 110, -1));

        jLabel13.setText("Modelo");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 20));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 10));

        jLabel14.setText("Veículo");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 20));

        jLabel15.setText("Cor");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 20, -1));

        jLabel16.setText("Ano");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));
        jPanel3.add(txModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 100, -1));
        jPanel3.add(txCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 110, -1));
        jPanel3.add(txAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        preencherCidades();
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btSalvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseReleased
        try {
            ClienteDAO.inserir(retornaObjeto());
        } catch (SQLException ex) {
            Logger.getLogger(jiCadCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarMouseReleased

    private void rbtnSimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSimMouseReleased
    cbCliente.setEnabled(true);
    txNome.setEnabled(false);
    ftxCpf.setEnabled(false);
    ftxTelefone.setEnabled(false);
    txRua.setEnabled(false);
    txNum.setEnabled(false);
    cbEstado.setEnabled(false);
    cbCidade.setEnabled(false);
    }//GEN-LAST:event_rbtnSimMouseReleased

    private void rbtnNaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnNaoMouseReleased
    cbCliente.setEnabled(false);
    txNome.setEnabled(true);
    ftxCpf.setEnabled(true);
    ftxTelefone.setEnabled(true);
    txRua.setEnabled(true);
    txNum.setEnabled(true);
    cbEstado.setEnabled(true);
    cbCidade.setEnabled(true);
    }//GEN-LAST:event_rbtnNaoMouseReleased

    private void btCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseReleased
       this.dispose();
    }//GEN-LAST:event_btCancelarMouseReleased

    private void cbChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChassiActionPerformed
     if(cbChassi.getSelectedIndex() == 0){
        txModelo.setText("");
        txAno.setText("");
        txCor.setText("");
        }else{
        try {    
        AutomovelBean automovel = AutomovelDAO.pesquisar(cbChassi.getSelectedItem().toString());
        txModelo.setText(automovel.getModelo().getNome());
        txAno.setText(Integer.toString(automovel.getAno()));
        txCor.setText(automovel.getCor());
        
        }catch (SQLException ex) {
            Logger.getLogger(CadFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbChassiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup btngSimNao;
    private javax.swing.JComboBox<String> cbChassi;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JFormattedTextField ftxCpf;
    private javax.swing.JFormattedTextField ftxTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JRadioButton rbtnNao;
    private javax.swing.JRadioButton rbtnSim;
    private javax.swing.JTextField txAno;
    private javax.swing.JTextField txCor;
    private javax.swing.JTextField txModelo;
    private javax.swing.JTextField txNome;
    private javax.swing.JTextField txNum;
    private javax.swing.JTextField txRua;
    // End of variables declaration//GEN-END:variables
}
