/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Bean.ModeloBean;
import DAO.ModeloDAO;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.plaf.metal.MetalBorders;

/**
 *
 * @author Talita
 */
public class jiCadModelo extends javax.swing.JInternalFrame {
     private boolean salvar =false;
    private int id = 0;
    
    /**
     * Creates new form jiModelo
     */
    public jiCadModelo() {
        initComponents();
        salvar = true;
    }
    
    public jiCadModelo(ModeloBean modelo) {
        initComponents();
        salvar = false;
        id = modelo.getIdModelo();
    }
    
    private void preencherCampos(ModeloBean modelo){
        txModelo.setText(modelo.getNome());
    }
    
    private ModeloBean retornaObjeto(){
        ModeloBean modelo = new ModeloBean();
        modelo.setNome(txModelo.getText().toUpperCase());
        modelo.setIdModelo(id);
        return modelo;
        
    }
    private boolean validaCampos(){
        boolean validador = true;
        txModelo.setText(txModelo.getText().trim());
        if(txModelo.getText().equals("")){
            validador = false;
            txModelo.setBorder(BorderFactory.createLineBorder(Color.red));
            lbMensagem.setText("*Campos obrigatorios não preenchidos!");
        }else{
            txModelo.setBorder(MetalBorders.getTextFieldBorder());
        }
        return validador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txModelo = new javax.swing.JTextField();
        lbMensagem = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Modelo de Automóveis");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));
        jPanel1.add(txModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 211, 20));
        jPanel1.add(lbMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, 20));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão salvar.png"))); // NOI18N
        btSalvar.setBorder(null);
        btSalvar.setBorderPainted(false);
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSalvarMouseReleased(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cancelar.png"))); // NOI18N
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btCancelarMouseReleased(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setBounds(0, 0, 382, 279);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseReleased
        if (validaCampos()){
            try{
                if(salvar){
                    ModeloDAO.inserir(retornaObjeto());
                    lbMensagem.setText("Salvo com sucesso");
                }else{
                    ModeloDAO.alterar(retornaObjeto());
                    lbMensagem.setText("Salvo com sucesso");
                }
                this.dispose();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btSalvarMouseReleased

    private void btCancelarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelarMouseReleased
        this.dispose();
    }//GEN-LAST:event_btCancelarMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JTextField txModelo;
    // End of variables declaration//GEN-END:variables
}
