/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Talita
 */
public class jiPesCidade extends javax.swing.JInternalFrame {

    /**
     * Creates new form jiPesCidade
     */
    public jiPesCidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesqCidade = new javax.swing.JTable();
        cbEstado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txCidade = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisa por Cidade");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("UF");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 20));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("");
        btPesquisar.setBorder(null);
        btPesquisar.setBorderPainted(false);
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 100, 30));

        tbPesqCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cidade", "UF"
            }
        ));
        tbPesqCidade.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPesqCidade.setAutoscrolls(false);
        tbPesqCidade.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbPesqCidade);
        tbPesqCidade.getAccessibleContext().setAccessibleName("Resultado de Pesquisa");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 450, 190));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 100, 20));

        jLabel2.setText("Cidade");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));
        jPanel1.add(txCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 240, -1));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cadastrar.png"))); // NOI18N
        btCadastrar.setBorder(null);
        btCadastrar.setBorderPainted(false);
        jPanel1.add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cancelar.png"))); // NOI18N
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão excluir.png"))); // NOI18N
        btExcluir.setBorder(null);
        btExcluir.setBorderPainted(false);
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 510, 390));

        setBounds(0, 0, 573, 447);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPesqCidade;
    private javax.swing.JTextField txCidade;
    // End of variables declaration//GEN-END:variables
}
