/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Talita
 */
public class jiPesAuto extends javax.swing.JInternalFrame {

    /**
     * Creates new form jiPesAuto
     */
    public jiPesAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txChassi = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        cbModelo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesqAuto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbMensagem = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Pesquisa por Automóvel");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chassi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 40, 20));
        jPanel1.add(txChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 240, 20));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão pesquisar.png"))); // NOI18N
        btPesquisar.setToolTipText("");
        btPesquisar.setBorder(null);
        btPesquisar.setBorderPainted(false);
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 100, 30));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cadastrar.png"))); // NOI18N
        btCadastrar.setBorder(null);
        btCadastrar.setBorderPainted(false);
        jPanel1.add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão cancelar.png"))); // NOI18N
        btCancelar.setBorder(null);
        btCancelar.setBorderPainted(false);
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botão excluir.png"))); // NOI18N
        btExcluir.setBorder(null);
        btExcluir.setBorderPainted(false);
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        cbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel1.add(cbModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, 20));

        tbPesqAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Chassi", "Modelo", "Cor", "Ano"
            }
        ));
        tbPesqAuto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbPesqAuto.setAutoscrolls(false);
        tbPesqAuto.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbPesqAuto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 450, 190));

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 20));
        jPanel1.add(lbMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 354, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setBounds(0, 0, 601, 442);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JTable tbPesqAuto;
    private javax.swing.JTextField txChassi;
    // End of variables declaration//GEN-END:variables
}
